### ISSUE TITLE
cgi deprecated in python 3.13

### ISSUE THREAD

**Issue by veenstrajelmer** [ecmwf/multiurl#14]
### What maintenance does this project need?

In my testbank, I now get the following warning:
```
  /opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/multiurl/http.py:10: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

Since I did not see an issue about it yet, it seemed wise to report it.

### Organisation

Deltares

**Comment by akrherz** [comment]
With python3.13 in the wild now, this is a problem see: conda-forge/cads-api-client-feedstock#18
